"""Pydantic data models for scene descriptions, ground truth, and evaluation results."""

from __future__ import annotations

from pydantic import BaseModel, Field


# ── VLM Output Schema ─────────────────────────────────────────────────────────


class DetectedObject(BaseModel):
    """A single detected object category in the scene."""

    category: str = Field(description="Object category, e.g. car, pedestrian, traffic_light")
    count: int = Field(description="Number of instances detected", ge=0)
    details: str = Field(
        default="",
        description="Spatial/contextual details, e.g. '2 cars ahead in same lane'",
    )


class SceneDescription(BaseModel):
    """Structured scene description generated by the VLM."""

    summary: str = Field(description="2-3 sentence overview of the driving scene")
    objects: list[DetectedObject] = Field(
        default_factory=list, description="Detected objects in the scene"
    )
    weather: str = Field(description="Weather condition: clear, rainy, foggy, snowy, overcast")
    lighting: str = Field(description="Lighting condition: daytime, night, dawn, dusk")
    road_type: str = Field(
        description="Road type: highway, city_street, residential, intersection, parking_lot"
    )
    hazards: list[str] = Field(
        default_factory=list,
        description="Potential hazards, e.g. 'pedestrian crossing ahead'",
    )
    meta_actions: list[str] = Field(
        default_factory=list,
        description="Recommended driving actions: brake, accelerate, lane_change_left, "
        "lane_change_right, yield, maintain_speed, stop, slow_down",
    )


# ── Ground Truth from BDD100K ─────────────────────────────────────────────────


class GroundTruth(BaseModel):
    """Ground truth extracted from BDD100K annotations."""

    image_name: str
    objects: dict[str, int] = Field(
        default_factory=dict, description="Category → count from BDD100K labels"
    )
    weather: str = Field(default="unknown")
    scene: str = Field(default="unknown")
    timeofday: str = Field(default="unknown")
    description: str = Field(
        default="", description="Templated natural language description from GT labels"
    )


# ── Evaluation ────────────────────────────────────────────────────────────────


class EvaluationResult(BaseModel):
    """Evaluation metrics for a single image + prompt combination."""

    image_name: str
    prompt_id: str
    bert_score_precision: float = 0.0
    bert_score_recall: float = 0.0
    bert_score_f1: float = 0.0
    hallucination_rate: float = 0.0
    false_positive_objects: list[str] = Field(default_factory=list)
    false_negative_objects: list[str] = Field(default_factory=list)
    completeness_score: float = 0.0
    judge_score: float | None = None
    judge_reasoning: str = ""


class PromptComparisonRow(BaseModel):
    """Aggregated metrics for a single prompt variant across all eval images."""

    prompt_id: str
    prompt_strategy: str
    n_images: int
    avg_bert_f1: float
    avg_hallucination_rate: float
    avg_completeness: float
    avg_judge_score: float | None = None
    weather_accuracy: float = 0.0
    lighting_accuracy: float = 0.0
